version: '3.8'
networks:
  default:
    name: linkshrink-network
    external: true
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/linkshrink
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkshrink
    ports:
      - "5432:5432"
    volumes:
      - linkshrink-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  linkshrink-db:
  redis-data: