"""empty message

Revision ID: d3166413e1c4
Revises: 
Create Date: 2024-01-11 15:43:14.555962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3166413e1c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_counter_id'), 'url_counter', ['id'], unique=False)
    op.create_table('url_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_metadata_client_id'), 'url_metadata', ['client_id'], unique=False)
    op.create_index(op.f('ix_url_metadata_id'), 'url_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_url_metadata_long_url'), 'url_metadata', ['long_url'], unique=False)
    op.create_index(op.f('ix_url_metadata_short_url'), 'url_metadata', ['short_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_metadata_short_url'), table_name='url_metadata')
    op.drop_index(op.f('ix_url_metadata_long_url'), table_name='url_metadata')
    op.drop_index(op.f('ix_url_metadata_id'), table_name='url_metadata')
    op.drop_index(op.f('ix_url_metadata_client_id'), table_name='url_metadata')
    op.drop_table('url_metadata')
    op.drop_index(op.f('ix_url_counter_id'), table_name='url_counter')
    op.drop_table('url_counter')
    # ### end Alembic commands ###
